version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pharmaiq
      POSTGRES_PASSWORD: pharmaiq_dev
      POSTGRES_DB: pharmaiq_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/docker/scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmaiq"]
      interval: 2s
      timeout: 2s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  # Consolidated API Backend
  api:
    image: node:20-alpine
    working_dir: /app/services/api-gateway
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      # Database
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: pharmaiq
      DATABASE_PASSWORD: pharmaiq_dev
      DATABASE_NAME: pharmaiq_db
      DATABASE_URL: postgresql://pharmaiq:pharmaiq_dev@postgres:5432/pharmaiq_db
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # AI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Elasticsearch
      ELASTICSEARCH_NODE: http://elasticsearch:9200
    volumes:
      # Mount the entire project so shared types work
      - .:/app
      # Named volumes for dependencies
      - api-node-modules:/app/services/api-gateway/node_modules
    command: sh -c "npm install && npx ts-node -r tsconfig-paths/register src/main.ts"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  # Web Frontend
  web:
    image: node:20-alpine
    working_dir: /app/web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://api:3001
    depends_on:
      - api
    volumes:
      # Source code for live editing
      - ./web/src:/app/web/src
      - ./web/public:/app/web/public
      - ./web/next.config.js:/app/web/next.config.js
      - ./web/tailwind.config.ts:/app/web/tailwind.config.ts
      - ./web/postcss.config.js:/app/web/postcss.config.js
      - ./web/tsconfig.json:/app/web/tsconfig.json
      - ./web/package.json:/app/web/package.json
      - ./web/jest.setup.js:/app/web/jest.setup.js
      # Named volumes for dependencies and build artifacts
      - web-node-modules:/app/web/node_modules
    command: sh -c "npm install --prefer-offline --no-audit --progress=false --legacy-peer-deps && npm run dev"

  # AI Worker
  ai-worker:
    image: node:20-alpine
    working_dir: /app/services/ai-worker
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./services/ai-worker/src:/app/services/ai-worker/src
      - ./services/ai-worker/package.json:/app/services/ai-worker/package.json
      - ./services/ai-worker/tsconfig.json:/app/services/ai-worker/tsconfig.json
      - ./shared:/app/shared
      - ai-worker-node-modules:/app/services/ai-worker/node_modules
    command: sh -c "npm install --prefer-offline --no-audit --progress=false --legacy-peer-deps && npm run start:dev"

  # Processing Worker
  processing-worker:
    image: node:20-alpine
    working_dir: /app/services/processing-worker
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: pharmaiq
      DATABASE_PASSWORD: pharmaiq_dev
      DATABASE_NAME: pharmaiq_db
      DATABASE_URL: postgresql://pharmaiq:pharmaiq_dev@postgres:5432/pharmaiq_db
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/processing-worker/src:/app/services/processing-worker/src
      - ./services/processing-worker/package.json:/app/services/processing-worker/package.json
      - ./services/processing-worker/tsconfig.json:/app/services/processing-worker/tsconfig.json
      - ./shared:/app/shared
      - processing-worker-node-modules:/app/services/processing-worker/node_modules
    command: sh -c "npm install --prefer-offline --no-audit --progress=false --legacy-peer-deps && npm run start:dev"

  # SEO Worker
  seo-worker:
    image: node:20-alpine
    working_dir: /app/services/seo-worker
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: pharmaiq
      DATABASE_PASSWORD: pharmaiq_dev
      DATABASE_NAME: pharmaiq_db
      DATABASE_URL: postgresql://pharmaiq:pharmaiq_dev@postgres:5432/pharmaiq_db
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/seo-worker/src:/app/services/seo-worker/src
      - ./services/seo-worker/package.json:/app/services/seo-worker/package.json
      - ./services/seo-worker/tsconfig.json:/app/services/seo-worker/tsconfig.json
      - ./shared:/app/shared
      - seo-worker-node-modules:/app/services/seo-worker/node_modules
    command: sh -c "npm install --prefer-offline --no-audit --progress=false --legacy-peer-deps && npm run start:dev"

volumes:
  # Database volumes
  postgres-data:
  redis-data:
  elasticsearch-data:
  # Named volumes for node_modules
  api-node-modules:
  web-node-modules:
  ai-worker-node-modules:
  processing-worker-node-modules:
  seo-worker-node-modules:

networks:
  default:
    name: pharmaiq-network