name: Docker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          cp .env.example .env
          echo "OPENAI_API_KEY=sk-test" >> .env
      
      - name: Run docker-compose up
        run: |
          # This is the actual command users will run
          docker-compose up -d
          
          # Wait for services to be ready
          echo "Waiting for services..."
          sleep 45
          
          # Check if everything is running
          docker-compose ps
          
          # Test endpoints
          curl -f http://localhost:3000 || echo "Frontend not ready yet"
          curl -f http://localhost:3001/health || echo "API not ready yet"
          
          # Show logs if there are issues
          docker-compose logs --tail=20
          
      - name: Cleanup
        if: always()
        run: docker-compose down -v