name: Test Docker Cross-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install docker
        colima start
        
    - name: Test Docker Compose
      run: |
        docker-compose config
        docker-compose up -d
        sleep 30
        docker-compose ps
        docker-compose exec -T postgres psql -U pharmaiq -d pharmaiq_db -c "SELECT 1;"
        docker-compose down -v